### PR TITLE
add bower support

### PR DESCRIPTION
**Pull request by theborakompanioni**
Prepares the repo for a grunt or gulp build process. Commits whole "bower_components" for safety reasons.

### CODE REVIEW

**Comment by theborakompanioni** [comment]
I have created a small fork with a build process for the ui. You can check it out on http://theborakompanioni.github.io/hive/#/ (repo: https://github.com/theborakompanioni/hive). See the client/apps/chesshive directory for the ui scripts.

If you are interested we could implement something alike for gamehub.

**Comment by benas** [comment]
Hi, that's great! What a neat UI you have :-) I love the countdown counter.

I'm interested in making the UI with [angular-chess](https://github.com/theborakompanioni/angular-chess), for sure. We can work in a separate branch for that, I was planning to keep the jQuery version alongside.

In regards to your PR, not sure we need to add all bower components in the repo, what would be unsafe if we run `bower install` to download components? I think we can keep the `bower.json` and the modification in the `README.md`.

Finally, If I had to choose between grunt and gulp, I would go for gulp. I have created an issue (#14) for that.

**Comment by theborakompanioni** [comment]
If you do not want bower_components committed it's perfectly fine. I just prefer to have them in my repository since I have already had very bad experiences with packages maintained on bower.

Yes.. the countdown - I am just messing around a bit. I chose grunt in the mentioned repository as I have more experience with it. But I like gulp and feel it is more superior.. so.. good choice. I hope I find the time to contribute over the next weeks.

OT: Currently I am trying to refactor quite a bit of code based on your work to create a more "universal" api. It'd be great to just instance a class of "GameX" and be able to play it via your server (with the corresponding ui of course). Let's talk about that some other time if your interested.

**Comment by benas** [comment]
Hey, please keep your PR, I was just asking about bower components.
Could you remove bower_components and keep the modifications in the `README.md` and the `bower.json` file? I'm ready to merge it.

> I have already had very bad experiences with packages maintained on bower.
It looks like [bower is dead](https://twitter.com/search?src=typd&q=bower%20is%20dead) ..

**Comment by theborakompanioni** [comment]
[Bower is alive](http://bower.io/blog/2015/bower-alive-looking-contributors/). But I changed my approach and want to set up a build process in another pull request. Is that fine with you?

**Comment by benas** [comment]
Yes, it was a rumor. They are looking for contributors to help keeping the work on bower up.

It's fine for me to work on the build process in a separate PR, may be try to implement feature #14 ?

**Pull request merged**
